apiVersion: extensions/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: demo-istio-pong
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-istio-pong
        version: v.0.0.2
    spec:
      containers:
      - name: demo-istio-pong
        image: docker.io/jsenon/demo-istio:develop
        env:
        - name: MY_VERSION
          value: "v.0.0.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 9010